//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.269
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientAdmin.ImageTransfertServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://schemas.datacontract.org/2004/07/ImageTransfertService")]
    [System.SerializableAttribute()]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string nameField;
        
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string role {
            get {
                return this.roleField;
            }
            set {
                if ((object.ReferenceEquals(this.roleField, value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageInfo", Namespace="http://schemas.datacontract.org/2004/07/ImageTransfertService")]
    [System.SerializableAttribute()]
    public partial class ImageInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string imageidField;
        
        private string albumidField;
        
        private string useridField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string imageid {
            get {
                return this.imageidField;
            }
            set {
                if ((object.ReferenceEquals(this.imageidField, value) != true)) {
                    this.imageidField = value;
                    this.RaisePropertyChanged("imageid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string albumid {
            get {
                return this.albumidField;
            }
            set {
                if ((object.ReferenceEquals(this.albumidField, value) != true)) {
                    this.albumidField = value;
                    this.RaisePropertyChanged("albumid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string userid {
            get {
                return this.useridField;
            }
            set {
                if ((object.ReferenceEquals(this.useridField, value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageTransfertServiceRef.IImageTransfert")]
    public interface IImageTransfert {
        
        // CODEGEN : La génération du contrat de message depuis l'opération authentify n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageTransfert/authentify", ReplyAction="http://tempuri.org/IImageTransfert/authentifyResponse")]
        ClientAdmin.ImageTransfertServiceRef.authentifyResponse authentify(ClientAdmin.ImageTransfertServiceRef.UserInfo request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ImageUploadRequest) du message ImageUploadRequest ne correspond pas à la valeur par défaut (UploadImage)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageTransfert/UploadImage", ReplyAction="http://tempuri.org/IImageTransfert/UploadImageResponse")]
        ClientAdmin.ImageTransfertServiceRef.ErrorMessage UploadImage(ClientAdmin.ImageTransfertServiceRef.ImageUploadRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ImageDownloadRequest) du message ImageDownloadRequest ne correspond pas à la valeur par défaut (Download)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageTransfert/Download", ReplyAction="http://tempuri.org/IImageTransfert/DownloadResponse")]
        ClientAdmin.ImageTransfertServiceRef.ImageDownloadResponse Download(ClientAdmin.ImageTransfertServiceRef.ImageDownloadRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (UserInfo) du message UserInfo ne correspond pas à la valeur par défaut (addUser)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageTransfert/addUser", ReplyAction="http://tempuri.org/IImageTransfert/addUserResponse")]
        ClientAdmin.ImageTransfertServiceRef.ErrorMessage addUser(ClientAdmin.ImageTransfertServiceRef.UserInfo request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (UserInfo) du message UserInfo ne correspond pas à la valeur par défaut (deleteUser)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageTransfert/deleteUser", ReplyAction="http://tempuri.org/IImageTransfert/deleteUserResponse")]
        ClientAdmin.ImageTransfertServiceRef.ErrorMessage deleteUser(ClientAdmin.ImageTransfertServiceRef.UserInfo request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ImageParam) du message ImageParam ne correspond pas à la valeur par défaut (createAlbum)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageTransfert/createAlbum", ReplyAction="http://tempuri.org/IImageTransfert/createAlbumResponse")]
        ClientAdmin.ImageTransfertServiceRef.ErrorMessage createAlbum(ClientAdmin.ImageTransfertServiceRef.ImageParam request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ImageParam) du message ImageParam ne correspond pas à la valeur par défaut (deleteAlbum)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageTransfert/deleteAlbum", ReplyAction="http://tempuri.org/IImageTransfert/deleteAlbumResponse")]
        ClientAdmin.ImageTransfertServiceRef.ErrorMessage deleteAlbum(ClientAdmin.ImageTransfertServiceRef.ImageParam request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ImageParam) du message ImageParam ne correspond pas à la valeur par défaut (deleteImage)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageTransfert/deleteImage", ReplyAction="http://tempuri.org/IImageTransfert/deleteImageResponse")]
        ClientAdmin.ImageTransfertServiceRef.ErrorMessage deleteImage(ClientAdmin.ImageTransfertServiceRef.ImageParam request);
        
        // CODEGEN : La génération du contrat de message depuis l'opération getAllUserNames n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageTransfert/getAllUserNames", ReplyAction="http://tempuri.org/IImageTransfert/getAllUserNamesResponse")]
        ClientAdmin.ImageTransfertServiceRef.ListResult getAllUserNames(ClientAdmin.ImageTransfertServiceRef.getAllUserNamesRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ImageParam) du message ImageParam ne correspond pas à la valeur par défaut (getAllAlbumNames)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageTransfert/getAllAlbumNames", ReplyAction="http://tempuri.org/IImageTransfert/getAllAlbumNamesResponse")]
        ClientAdmin.ImageTransfertServiceRef.ListResult getAllAlbumNames(ClientAdmin.ImageTransfertServiceRef.ImageParam request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ImageParam) du message ImageParam ne correspond pas à la valeur par défaut (getAllImageName)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageTransfert/getAllImageName", ReplyAction="http://tempuri.org/IImageTransfert/getAllImageNameResponse")]
        ClientAdmin.ImageTransfertServiceRef.ListResult getAllImageName(ClientAdmin.ImageTransfertServiceRef.ImageParam request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ClientAdmin.ImageTransfertServiceRef.UserData data;
        
        public UserInfo() {
        }
        
        public UserInfo(ClientAdmin.ImageTransfertServiceRef.UserData data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authentifyResponse {
        
        public authentifyResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImageUploadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImageUploadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ClientAdmin.ImageTransfertServiceRef.ImageInfo ImageInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream ImageData;
        
        public ImageUploadRequest() {
        }
        
        public ImageUploadRequest(ClientAdmin.ImageTransfertServiceRef.ImageInfo ImageInfo, System.IO.Stream ImageData) {
            this.ImageInfo = ImageInfo;
            this.ImageData = ImageData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ErrorMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ErrorMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string message;
        
        public ErrorMessage() {
        }
        
        public ErrorMessage(string message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImageDownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImageDownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ClientAdmin.ImageTransfertServiceRef.ImageInfo ImageInfo;
        
        public ImageDownloadRequest() {
        }
        
        public ImageDownloadRequest(ClientAdmin.ImageTransfertServiceRef.ImageInfo ImageInfo) {
            this.ImageInfo = ImageInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImageDownloadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImageDownloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream ImageData;
        
        public ImageDownloadResponse() {
        }
        
        public ImageDownloadResponse(System.IO.Stream ImageData) {
            this.ImageData = ImageData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImageParam", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImageParam {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ClientAdmin.ImageTransfertServiceRef.ImageInfo info;
        
        public ImageParam() {
        }
        
        public ImageParam(ClientAdmin.ImageTransfertServiceRef.ImageInfo info) {
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllUserNamesRequest {
        
        public getAllUserNamesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListResult", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] names;
        
        public ListResult() {
        }
        
        public ListResult(string[] names) {
            this.names = names;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImageTransfertChannel : ClientAdmin.ImageTransfertServiceRef.IImageTransfert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageTransfertClient : System.ServiceModel.ClientBase<ClientAdmin.ImageTransfertServiceRef.IImageTransfert>, ClientAdmin.ImageTransfertServiceRef.IImageTransfert {
        
        public ImageTransfertClient() {
        }
        
        public ImageTransfertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageTransfertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageTransfertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageTransfertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAdmin.ImageTransfertServiceRef.authentifyResponse ClientAdmin.ImageTransfertServiceRef.IImageTransfert.authentify(ClientAdmin.ImageTransfertServiceRef.UserInfo request) {
            return base.Channel.authentify(request);
        }
        
        public void authentify(ClientAdmin.ImageTransfertServiceRef.UserData data) {
            ClientAdmin.ImageTransfertServiceRef.UserInfo inValue = new ClientAdmin.ImageTransfertServiceRef.UserInfo();
            inValue.data = data;
            ClientAdmin.ImageTransfertServiceRef.authentifyResponse retVal = ((ClientAdmin.ImageTransfertServiceRef.IImageTransfert)(this)).authentify(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAdmin.ImageTransfertServiceRef.ErrorMessage ClientAdmin.ImageTransfertServiceRef.IImageTransfert.UploadImage(ClientAdmin.ImageTransfertServiceRef.ImageUploadRequest request) {
            return base.Channel.UploadImage(request);
        }
        
        public string UploadImage(ClientAdmin.ImageTransfertServiceRef.ImageInfo ImageInfo, System.IO.Stream ImageData) {
            ClientAdmin.ImageTransfertServiceRef.ImageUploadRequest inValue = new ClientAdmin.ImageTransfertServiceRef.ImageUploadRequest();
            inValue.ImageInfo = ImageInfo;
            inValue.ImageData = ImageData;
            ClientAdmin.ImageTransfertServiceRef.ErrorMessage retVal = ((ClientAdmin.ImageTransfertServiceRef.IImageTransfert)(this)).UploadImage(inValue);
            return retVal.message;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAdmin.ImageTransfertServiceRef.ImageDownloadResponse ClientAdmin.ImageTransfertServiceRef.IImageTransfert.Download(ClientAdmin.ImageTransfertServiceRef.ImageDownloadRequest request) {
            return base.Channel.Download(request);
        }
        
        public System.IO.Stream Download(ClientAdmin.ImageTransfertServiceRef.ImageInfo ImageInfo) {
            ClientAdmin.ImageTransfertServiceRef.ImageDownloadRequest inValue = new ClientAdmin.ImageTransfertServiceRef.ImageDownloadRequest();
            inValue.ImageInfo = ImageInfo;
            ClientAdmin.ImageTransfertServiceRef.ImageDownloadResponse retVal = ((ClientAdmin.ImageTransfertServiceRef.IImageTransfert)(this)).Download(inValue);
            return retVal.ImageData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAdmin.ImageTransfertServiceRef.ErrorMessage ClientAdmin.ImageTransfertServiceRef.IImageTransfert.addUser(ClientAdmin.ImageTransfertServiceRef.UserInfo request) {
            return base.Channel.addUser(request);
        }
        
        public string addUser(ClientAdmin.ImageTransfertServiceRef.UserData data) {
            ClientAdmin.ImageTransfertServiceRef.UserInfo inValue = new ClientAdmin.ImageTransfertServiceRef.UserInfo();
            inValue.data = data;
            ClientAdmin.ImageTransfertServiceRef.ErrorMessage retVal = ((ClientAdmin.ImageTransfertServiceRef.IImageTransfert)(this)).addUser(inValue);
            return retVal.message;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAdmin.ImageTransfertServiceRef.ErrorMessage ClientAdmin.ImageTransfertServiceRef.IImageTransfert.deleteUser(ClientAdmin.ImageTransfertServiceRef.UserInfo request) {
            return base.Channel.deleteUser(request);
        }
        
        public string deleteUser(ClientAdmin.ImageTransfertServiceRef.UserData data) {
            ClientAdmin.ImageTransfertServiceRef.UserInfo inValue = new ClientAdmin.ImageTransfertServiceRef.UserInfo();
            inValue.data = data;
            ClientAdmin.ImageTransfertServiceRef.ErrorMessage retVal = ((ClientAdmin.ImageTransfertServiceRef.IImageTransfert)(this)).deleteUser(inValue);
            return retVal.message;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAdmin.ImageTransfertServiceRef.ErrorMessage ClientAdmin.ImageTransfertServiceRef.IImageTransfert.createAlbum(ClientAdmin.ImageTransfertServiceRef.ImageParam request) {
            return base.Channel.createAlbum(request);
        }
        
        public string createAlbum(ClientAdmin.ImageTransfertServiceRef.ImageInfo info) {
            ClientAdmin.ImageTransfertServiceRef.ImageParam inValue = new ClientAdmin.ImageTransfertServiceRef.ImageParam();
            inValue.info = info;
            ClientAdmin.ImageTransfertServiceRef.ErrorMessage retVal = ((ClientAdmin.ImageTransfertServiceRef.IImageTransfert)(this)).createAlbum(inValue);
            return retVal.message;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAdmin.ImageTransfertServiceRef.ErrorMessage ClientAdmin.ImageTransfertServiceRef.IImageTransfert.deleteAlbum(ClientAdmin.ImageTransfertServiceRef.ImageParam request) {
            return base.Channel.deleteAlbum(request);
        }
        
        public string deleteAlbum(ClientAdmin.ImageTransfertServiceRef.ImageInfo info) {
            ClientAdmin.ImageTransfertServiceRef.ImageParam inValue = new ClientAdmin.ImageTransfertServiceRef.ImageParam();
            inValue.info = info;
            ClientAdmin.ImageTransfertServiceRef.ErrorMessage retVal = ((ClientAdmin.ImageTransfertServiceRef.IImageTransfert)(this)).deleteAlbum(inValue);
            return retVal.message;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAdmin.ImageTransfertServiceRef.ErrorMessage ClientAdmin.ImageTransfertServiceRef.IImageTransfert.deleteImage(ClientAdmin.ImageTransfertServiceRef.ImageParam request) {
            return base.Channel.deleteImage(request);
        }
        
        public string deleteImage(ClientAdmin.ImageTransfertServiceRef.ImageInfo info) {
            ClientAdmin.ImageTransfertServiceRef.ImageParam inValue = new ClientAdmin.ImageTransfertServiceRef.ImageParam();
            inValue.info = info;
            ClientAdmin.ImageTransfertServiceRef.ErrorMessage retVal = ((ClientAdmin.ImageTransfertServiceRef.IImageTransfert)(this)).deleteImage(inValue);
            return retVal.message;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAdmin.ImageTransfertServiceRef.ListResult ClientAdmin.ImageTransfertServiceRef.IImageTransfert.getAllUserNames(ClientAdmin.ImageTransfertServiceRef.getAllUserNamesRequest request) {
            return base.Channel.getAllUserNames(request);
        }
        
        public string[] getAllUserNames() {
            ClientAdmin.ImageTransfertServiceRef.getAllUserNamesRequest inValue = new ClientAdmin.ImageTransfertServiceRef.getAllUserNamesRequest();
            ClientAdmin.ImageTransfertServiceRef.ListResult retVal = ((ClientAdmin.ImageTransfertServiceRef.IImageTransfert)(this)).getAllUserNames(inValue);
            return retVal.names;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAdmin.ImageTransfertServiceRef.ListResult ClientAdmin.ImageTransfertServiceRef.IImageTransfert.getAllAlbumNames(ClientAdmin.ImageTransfertServiceRef.ImageParam request) {
            return base.Channel.getAllAlbumNames(request);
        }
        
        public string[] getAllAlbumNames(ClientAdmin.ImageTransfertServiceRef.ImageInfo info) {
            ClientAdmin.ImageTransfertServiceRef.ImageParam inValue = new ClientAdmin.ImageTransfertServiceRef.ImageParam();
            inValue.info = info;
            ClientAdmin.ImageTransfertServiceRef.ListResult retVal = ((ClientAdmin.ImageTransfertServiceRef.IImageTransfert)(this)).getAllAlbumNames(inValue);
            return retVal.names;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientAdmin.ImageTransfertServiceRef.ListResult ClientAdmin.ImageTransfertServiceRef.IImageTransfert.getAllImageName(ClientAdmin.ImageTransfertServiceRef.ImageParam request) {
            return base.Channel.getAllImageName(request);
        }
        
        public string[] getAllImageName(ClientAdmin.ImageTransfertServiceRef.ImageInfo info) {
            ClientAdmin.ImageTransfertServiceRef.ImageParam inValue = new ClientAdmin.ImageTransfertServiceRef.ImageParam();
            inValue.info = info;
            ClientAdmin.ImageTransfertServiceRef.ListResult retVal = ((ClientAdmin.ImageTransfertServiceRef.IImageTransfert)(this)).getAllImageName(inValue);
            return retVal.names;
        }
    }
}
